
services:
  mariadb:
    image: mariadb:11.4
    container_name: movieDatabaseDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: movieDatabaseDB
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - movieDatabaseNetwork

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: movieDatabase-keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - movieDatabaseNetwork

volumes:
  mariadb_data:

networks:
  movieDatabaseNetwork:
    driver: bridge