spring.application.name=movieDatabase
server.port=8081

# ==== DATASOURCE ====
spring.datasource.url=jdbc:mariadb://localhost:3306/movieDatabaseDB
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ==== JPA / HIBERNATE ====
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# ==== FLYWAY ====
spring.flyway.enabled=true
spring.flyway.locations=filesystem:migrations

# ==== KEYCLOAK ====
keycloak.server-url=http://localhost:8080
keycloak.realm=movie-database-realm
keycloak.admin-client-id=admin-cli
keycloak.user-client-id=springboot-client
keycloak.admin-client-id-secret=${KEYCLOAK_SECRET}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/${keycloak.realm}

app.generic-admin-ensure-exists=true
app.generic-admin-email=${GENERIC_ADMIN_EMAIL}
app.generic-admin-password=${GENERIC_ADMIN_PASSWORD}

# ==== LOGGING (configured in logback.xml) ====
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.web.access=INFO
logging.level.org.springframework.security.oauth2=INFO
logging.level.cz.osu.prf.kip.favouriteLinks=DEBUG
